overflow: False
binning:
    - ["binvar0", "np.array([200,210,220,230,240,250,260,280,300,340,380,420,480,560,660,760,900])"]
    - ["binvar1", "np.array([-200,-190,-180,-170,-160,-150,-140,-130,-120,-110,-100,-90,-80,-70,-60,-50,-40,-30,-20,-10,0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200])"]
data:
    preproc:
        - "df: df.reset_index()"
        - "df: df.loc[df.eval(\"(varname0=='ZCand_pt') & (varname1=='METnoX_ptParaZCandCent')\")]"
    channel_processes:
        - name: ["DoubleMuon", "data_obs", 0]
          eval: "df: df.loc[df.eval(\"(selection=='DoubleMuon') & (parent=='MET')\")]"
        - name: ["DoubleElectron", "data_obs", 0]
          eval: "df: df.loc[df.eval(\"(selection=='DoubleElectron') & (parent=='SingleElectron')\")]"
mc:
    preproc:
        - "df: df.reset_index()"
        - "df: df.loc[df.eval(\"(varname0=='ZCand_pt') & (varname1=='METnoX_ptParaZCandCent')\")]"
        - "df: df.groupby(['varname0', 'varname1', 'selection', 'parent', 'binvar0', 'binvar1']).sum().reset_index()"
    channel_processes:
        - name: ["DoubleMuon", "DYJetsToMuMu", 0]
          eval: "df: df.loc[(df.selection=='DoubleMuon') & (df.parent=='DYJetsToMuMu')]"
        - name: ["DoubleMuon", "Backgrounds", 1]
          eval: "df: df.loc[(df.selection=='DoubleMuon') & (df.parent!='DYJetsToMuMu')]"
        - name: ["DoubleElectron", "DYJetsToEE", 0]
          eval: "df: df.loc[(df.selection=='DoubleElectron') & (df.parent=='DYJetsToEE')]"
        - name: ["DoubleElectron", "Backgrounds", 1]
          eval: "df: df.loc[(df.selection=='DoubleElectron') & (df.parent!='DYJetsToEE')]"
    systs: [
        "d1kqcd", "d2kqcd", "d3kqcd", "d1kew", "d2keww", "d2kewz", "d3keww", "d3kewz", "dkmix",
        "eleIdIsoTight", "eleIdIsoVeto", "eleReco", "eleTrig",
        "muonIdLoose", "muonIdTight", "muonIsoLoose", "muonIsoTight", "muonTrig",
        "photonIdLoose", "photonPixelSeedVeto",
        "tauIdTight",
        "btagSF",
        "metTrigStat",
        "pileup", "prefiring",
        "pdfscale", "alphas", "qcdF", "qcdR", "qcdFqcdR",
        "jesTotal", "jerSF", "unclust",
        "eleEnergyScale", "muonPtScale", "photonEnergyScale",
    ]
    add_syst: {}
params:
    - ["*", "autoMCStats", "10", "1"]
